### ISSUE TITLE
Padronização dos nos plots do município [To-Do List]

### ISSUE THREAD

**Issue by vsudbrack** [covid19br/covid19br.github.io#74]
Padronização dos plots por task (oriundas da reunião do #visual em 27/MAI):

**-  Mudar todos os gráficos para começarem no mesmo dia, 1º/MAR:**

- [ ] Casos diários/acumulados de SRAG (atualmente 9/FEV) 
- [ ] Óbitos diários/acumulados por COVID/SRAG (atualmente 20/MAR)
- [ ] TD de Casos SRAG (atualmente 16/MAR)
- [ ] TD de Óbitos SRAG (atualmente 9/FEV)
- [ ] TD de Óbitos COVID (atualmente 20/MAR)
- [ ] R de COVID (atualmente 5/MAR)
- [ ] R de SRAG (atualmente 16/MAR)
(Acredito que o "leitos" precise ficar em 8/MAR...)

**-  Mudar todos os gráficos para xlabel "%d/%3s":**
- [ ] Alterar formato do Leitos Ocupados (atualmente "%s %d")

- Testar a visualização com gridding vertical para orientar datas (discutir sobre isso no Slack #visuals)

**- Padronizar o estilo de gráfico como "pontos com linha" pois facilita a identificação de datas**
- [ ] Gráfico acumulado de casos/óbitos com pontos, assim como os gráficos da página "Estados". 
- [ ] Ao invés de ter duas linhas, ter a cor do ponto como função de seu status (Notificado para mais de 40 dias, Estimado para menos de 40 dias), assim como nos Diários. Discutir no #visuals a melhor representação para as projeções nesse plot.

**- Padronização dos y-labels**
- [ ] Nos gráficos em escala logaritmica (casos acumulados, óbitos acumulados) implementar algoritmo do Badain que troca "1000" por "1 mil", "10000" por "10 mil", etc.
- [ ] No R de SRAG, trocar ylabel de "%.1f" para "%.0f" (isto é "3.0" para "3", etc..)

**- Padronização dos x-labels**
- [ ] Trocar "Dia" por "Data", afinal informa Dia/Mês.
- [ ] No gráfico de óbitos diários/acumulados adicionar "Data do óbito"
- [ ] No gráfico de leitos ocupados, TD e R adicionar xlabel "Data"

**- Shadding dos casos/óbitos diários**
- [ ] Trocaram as cores dos pontos azuis para vermelho, porém agora são pontos vermelhos com a faixa de incerteza azul. Trocá-la também para vermelho.

**- Padronizar as legendas em caixas abaixo do título**
- [ ]  Adicionar título no gráfico "Leitos Ocupados"
- [ ]  Adicionar três caixas de Azul-Observado, Vermelho-Corrigido*, Preto-Modelo
- [ ]  Remover as palavras "Observado Corrigido Modelo" da parte interna do gráfico
*Mudar "Corrigido" para "Estimado" para manter a nomenclatura do site concisa. (Verificar com Diogro se ambas são a mesma coisa...)

**- [ ] Padronizar tamanho das fontes**

Discussões e sugestões mais que bem-vindas no canal #visuals do Slack!

**Comment by renatocoutinho** [comment]
gente, tudo que é SRAG tem que plotar só a partir de 16/03, antes disso não dá pra usar. Você pode até colcoar o eixo x começando em 01/03, mas não pode pôr os pontos

**Comment by vsudbrack** [comment]
Porque Renato? Já tem casos de covid em Sampa em 26/FEV...

**Comment by renatocoutinho** [comment]
Sim, mas foi só no dia 15/03 que passou a ser obrigatória a notificação de casos SRAG - antes disso apenas hospitais sentinela reportavam isso. Então você tá comparando coisas que não são comparáveis.
